[package]
name = "stretch_please"
version = "0.1.0"
edition = "2021"

[dependencies]
dotenv = "0.15.0"
image = { version = "0.25.5", features = ["nasm"] }
poise = "0.6.1"
rand = "0.8.5"
serenity = "0.12.2"
tokio = { version = "1.41.1", features = ["rt-multi-thread"] }
